[package]
name = "monkeybagel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
hex = "0.4.3"
pgp = "0.12.0-alpha.1"
rpgpie = { path = "../rpgpie" }
rpgpie-cert-store = { path = "../rpgpie-cert-store" }

[dev-dependencies]
rstest = "0.18.2"
testresult = "0.4.0"
