[package]
name = "monkeybagel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
pgp = "0.11.0"
rpgpie = { path = "../rpgpie" }
rpgpie-cert-store = { path = "../rpgpie-cert-store" }
