name: CI

on:
  pull_request:
  push:
    tags:
      - 'v*'
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-spelling:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - name: Check spelling
        uses: codespell-project/actions-codespell@master

  formatting:
    name: Check formatting
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          install-libs: true
        - os: macos-latest
        - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ matrix.install-libs }}
        run: sudo apt-get install -y pcscd libpcsclite-dev
      - name: Check formatting
        run: cargo fmt --all -- --check

  tests:
    name: Unit tests
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          install-libs: "sudo apt-get install -y pcscd libpcsclite-dev"
        - os: macos-latest
        - os: windows-latest
          install-libs: "vcpkg install sqlite3:x64-windows"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ matrix.install-libs }}
        run: ${{ matrix.install-libs }}
      - name: Build and test
        run: cargo build --verbose --all && cargo test --verbose --all

  lints:
    name: Clippy lints
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          install-libs: true
        - os: macos-latest
        - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ matrix.install-libs }}
        run: sudo apt-get install -y pcscd libpcsclite-dev
      - name: Check for lints
        run: cargo clippy -- -D warnings
